### ISSUE TITLE
"Go public"-checklist

### ISSUE THREAD

**Issue by toshify** [nodepa/seedling#397]
"Go public"-[checklist](https://opensource.guide/starting-a-project/#your-pre-launch-checklist)
- [x] Re-write commit history to follow our [Commit Guidelines](/nodepa/seedling/.gitmessage)
- [x] Move language assets to \<root\>/content + cc license
- [x] Add Privacy Policy and EULA/Terms of Use
- [x] Set repo to `public`
- [x] Check Insights > Community checkup
- [x] Turn on wiki ???
- [x] Add PR review requirement
- [x] Check dependency graph under Insights
- [x] Verify contact links on PR is correct
